### PR TITLE
login/logout button, extra white space and username in dropdown menu

### LINKED ISSUE #4: Extra white space in Dropdown menu
**Describe the bug**
when user is logged out then there is "white space" in the place of user's name when user logged in

**To Reproduce**
1. log out
2. Click on top right menu
3. Hover 5px above create text

**Expected behavior**
There should not be any extra space if the user is not logged in / when user is sign out

**Screenshots**
extra-whitespace-in-menu-twtai

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: edge
 - Version -

**Smartphone (please complete the following information):**

**Additional context**
No

### PR DESCRIPTION
**Pull request by gouravg8**
fixes: #4 #7 #8 
image

### CODE REVIEW

File: src/components/layout/NavBar.tsx [hunk 1]
```diff
@@ -35,17 +39,33 @@ const NavBar = async () => {
...
 				>
-					<Link href={"/profile"}>
-						<DropdownMenuItem className="text-base font-semibold">
-							{/* TODO: add the user name if Logged in */}
-						</DropdownMenuItem>
-					</Link>
+					{user && (
+						<Link href={"/profile"}>
+							<DropdownMenuItem className="text-base font-semibold cursor-pointer">
+								{/* TODO: add the user name if Logged in */}
```
Comment (gouravg8) [inline src/components/layout/NavBar.tsx]: remove commented codes

File: src/components/layout/NavBar.tsx [hunk 2]
```diff
@@ -35,17 +39,33 @@ const NavBar = async () => {
...
-						<DropdownMenuItem>Create</DropdownMenuItem>
+						<DropdownMenuItem className="cursor-pointer">
+							Create
+						</DropdownMenuItem>
 					</Link>
-					<DropdownMenuItem>Billing</DropdownMenuItem>
+					<DropdownMenuItem className="cursor-pointer">
+						Billing
+					</DropdownMenuItem>
 					{/* TODO: show login/signout based on user logged in or not */}
```
Comment (gouravg8) [inline src/components/layout/NavBar.tsx]: remove this also
